[package]
name = "lcr"
version = "0.1.0"
authors = ["Ephraim Kunz <ephraimkunz@me.com>"]
edition = "2018"

[[bin]]
name = "lcr"
path = "src/main.rs"

[lib]
name = "lcr"

[dependencies]
reqwest = {version = "0.10", features = ["blocking", "json"]}
anyhow = "1.0"
headless_chrome = "0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }